### ISSUE TITLE
The Build for Codenvy SDK is failing on ubuntu 14.04 : Note JDK is oracle 1.8(not sure it matters) looks like it fails also on jdk 1.7

### ISSUE THREAD

**Issue by MezzLabs** [codenvy/assembly-che#3]
------------------------------------------------------------------------
[INFO] Building Codenvy SDK :: Assemblies Tomcat 3.8.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6:clean (default-clean) @ assembly-sdk ---
[INFO] Deleting /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:parse-version (parse-version) @ assembly-sdk ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ assembly-sdk ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ assembly-sdk ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ assembly-sdk ---
[INFO] 
[INFO] --- maven-sortpom-plugin:2.3.0:verify (default) @ assembly-sdk ---
[INFO] Verifying file /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/pom.xml
[INFO] 
[INFO] --- license-maven-plugin:2.8:check (check-headers) @ assembly-sdk ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:copy (copy-clear-tomcat) @ assembly-sdk ---
[INFO] Configured Artifact: org.apache.tomcat:tomcat:7.0.50:zip
[INFO] Copying tomcat-7.0.50.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tomcat.zip
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:copy-dependencies (copy-dependencies-war) @ assembly-sdk ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:copy (copy-tomcat-libs) @ assembly-sdk ---
[INFO] Configured Artifact: org.slf4j:log4j-over-slf4j:1.7.6:jar
[INFO] Configured Artifact: org.slf4j:slf4j-api:1.7.6:jar
[INFO] Configured Artifact: org.slf4j:jul-to-slf4j:1.7.6:jar
[INFO] Configured Artifact: ch.qos.logback:logback-core:1.1.2:jar
[INFO] Configured Artifact: ch.qos.logback:logback-classic:1.1.2:jar
[INFO] Configured Artifact: com.codenvy.ide:codenvy-ssl-socket-factory:1.11.0-SNAPSHOT:jar
[INFO] Copying log4j-over-slf4j-1.7.6.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/lib/log4j-over-slf4j.jar
[INFO] Copying slf4j-api-1.7.6.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/lib/slf4j-api.jar
[INFO] Copying jul-to-slf4j-1.7.6.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/lib/jul-to-slf4j.jar
[INFO] Copying logback-core-1.1.2.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/lib/logback-core.jar
[INFO] Copying logback-classic-1.1.2.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/lib/logback-classic.jar
[INFO] Copying codenvy-ssl-socket-factory-1.11.0-SNAPSHOT.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/lib/codenvy-ssl-socket-factory.jar
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:copy (copy-tutorials) @ assembly-sdk ---
[INFO] Configured Artifact: com.codenvy.plugin-sdk:action-api-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:theme-api-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:notification-api-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:parts-api-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:editor-api-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:gin-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:gist-extension:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:empty-extension:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:helloworld-extension:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:analytics-event-logger-extension:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:icons-registry-api:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:wysiwyg-editor-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Configured Artifact: com.codenvy.plugin-sdk:server-side-tutorial:1.8.0-SNAPSHOT:zip
[INFO] Copying action-api-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/action-api-tutorial.zip
[INFO] Copying theme-api-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/theme-api-tutorial.zip
[INFO] Copying notification-api-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/notification-api-tutorial.zip
[INFO] Copying parts-api-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/parts-api-tutorial.zip
[INFO] Copying editor-api-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/editor-api-tutorial.zip
[INFO] Copying gin-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/gin-tutorial.zip
[INFO] Copying gist-extension-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/gist-extension.zip
[INFO] Copying empty-extension-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/empty-extension.zip
[INFO] Copying helloworld-extension-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/helloworld-extension.zip
[INFO] Copying analytics-event-logger-extension-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/analytics-event-logger-extension.zip
[INFO] Copying icons-registry-api-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/icons-registry-api-tutorial.zip
[INFO] Copying wysiwyg-editor-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/wysiwyg-editor-tutorial.zip
[INFO] Copying server-side-tutorial-1.8.0-SNAPSHOT.zip to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tutorials/server-side-tutorial.zip
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:copy (copy-sdk-tools) @ assembly-sdk ---
[INFO] Configured Artifact: com.codenvy.plugin-sdk:codenvy-sdk-tools:jar-with-dependencies:1.8.0-SNAPSHOT:jar
[INFO] Copying codenvy-sdk-tools-1.8.0-SNAPSHOT-jar-with-dependencies.jar to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/sdk-tools/codenvy-sdk-tools.jar
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (Prepare Tomcat) @ assembly-sdk ---
[INFO] Executing tasks

main:
    [unzip] Expanding: /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/zip/tomcat.zip into /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target
     [move] Moving 57 files to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target
     [move] Moved 8 empty directories to 3 empty directories under /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target
     [copy] Copying 64 files to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/tomcat
     [copy] Copied 9 empty directories to 3 empty directories under /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/tomcat
     [copy] Copying 15 files to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide
     [move] Moving 1 file to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/bin
   [delete] Deleting: /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/bin/catalina.bat
     [copy] Copying 10 files to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/sdk-resources
    [unwar] Expanding: /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/war/assembly-ide-3.8.0-SNAPSHOT.war into /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/war/ws
     [move] Moving 691 files to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/packager-conf/war/ws/_app
     [move] Moving 13 files to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/tutorials
      [war] Building war: /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/webapps/ws.war
     [copy] Copying 1 file to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/webapps
     [copy] Copying 1 file to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/webapps
     [copy] Copying 1 file to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/webapps
     [copy] Copying 1 file to /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/tomcat-ide/webapps
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources) @ assembly-sdk ---
[INFO] 
[INFO] --- maven-assembly-plugin:2.5:single (tomcat-zip) @ assembly-sdk ---
[INFO] Reading assembly descriptor: /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/src/main/assembly/tomcat-archive.xml
[INFO] Building zip: /home/sreekanth/codenvy/assembly-che/sdk/assembly-sdk/target/codenvy-3.8.0-SNAPSHOT.zip
[ERROR] Java heap space -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
sreekanth@ide:~/codenvy/assembly-che$

**Comment by benoitf** [comment]
Did you try with more memory ? with setting property like
```
export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"
```
before running it

**Comment by skabashnyuk** [comment]
or you can use https://github.com/codenvy/assembly-che/blob/master/build.sh
We already preconfigure XX:MaxPermSize in that script
